name: My First Workflow

on: push

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: List and Read Files
        run: |
            echo "My First Github Actions job"
            ls -al
            cat README.md
      
      - name: Generate ASCII Artwork
        run: cowsay -f dragon "Run for cover, I'm a DRAGON ....RAWRRR" >> dragon.txt

    #   - name: List files
    #     run: ls -la

    #   - name: Read file
    #     run: cat README.md
